---
all:
  children:
    production:
      hosts:
        server:
          ansible_host: "{{ lookup('env', 'TARGET_SERVER') }}"
          ansible_user: "{{ lookup('env', 'SSH_USER') }}"
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
          ansible_python_interpreter: /usr/bin/python3