name: Deploy to Production

on:
  workflow_run:
    workflows: ["Fitness Booking CI/CD Pipeline"]
    types:
      - completed
    branches: [main, master]

jobs:
  deploy:
    name: Deploy with Ansible
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
      
      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          TARGET_SERVER: ${{ secrets.TARGET_SERVER }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          APP_PORT: ${{ secrets.APP_PORT }}
          NGINX_HTTP_PORT: ${{ secrets.NGINX_HTTP_PORT }}
          NGINX_HTTPS_PORT: ${{ secrets.NGINX_HTTPS_PORT }}
        run: |
          cd ansible
          ansible-playbook -i inventory.yml deploy.yml